
CREATE TABLE APP_RESOURCE
(
	RESOURCE_ID  INTEGER NULL,
	ACCESS_TYPE  VARCHAR(100) NULL
)
;



ALTER TABLE APP_RESOURCE
	ADD  PRIMARY KEY (RESOURCE_ID)
;



CREATE TABLE CATEGORY
(
	CATEGORY_ID  INTEGER NULL,
	NAME  VARCHAR(32) NULL,
	DESCRIPTION  VARCHAR(64) NULL,
	PARENT  INTEGER NULL,
	IDENTIFIER  VARCHAR(20) NULL
)
;



ALTER TABLE CATEGORY
	ADD  PRIMARY KEY (CATEGORY_ID)
;



CREATE TABLE ORDER_PRODUCT
(
	ORDER_PRODUCT_ID  INTEGER NULL,
	PRODUCT_ID  INTEGER NOT NULL,
	ORDER_ID  INTEGER NOT NULL,
	QTY  INTEGER NULL,
	TOTAL  INTEGER NULL
)
;



ALTER TABLE ORDER_PRODUCT
	ADD  PRIMARY KEY (ORDER_PRODUCT_ID)
;



CREATE TABLE ORDER_STATUS
(
	ORDER_STATUS_ID  INTEGER NULL,
	NAME  VARCHAR(32) NULL,
	DESCRIPTION  VARCHAR(100) NULL
)
;



ALTER TABLE ORDER_STATUS
	ADD  PRIMARY KEY (ORDER_STATUS_ID)
;



CREATE TABLE PRODUCT
(
	PRODUCT_ID  INTEGER NULL,
	PRODUCT_NAME  VARCHAR(50) NULL,
	PRICE  INTEGER NULL,
	DESCRIPTION  VARCHAR(500) NULL,
	QTY  INTEGER NULL,
	QTY_RESERVE  INTEGER NULL,
	QTY_HOLD  INTEGER NULL,
	RECEIPT_DATE  DATE NULL,
	CATEGORY_ID  INTEGER NOT NULL,
	CREATED_BY  VARCHAR(32) NULL,
	CREATED_DATE  DATE NULL,
	EDIT_DATE  DATE NULL,
	EDIT_BY  VARCHAR(32) NULL,
	TYPE_ID  INTEGER NULL
)
;



ALTER TABLE PRODUCT
	ADD  PRIMARY KEY (PRODUCT_ID)
;



CREATE TABLE PRODUCT_ATTRIBUTE
(
	PRODUCT_ID  INTEGER NOT NULL,
	NAME  VARCHAR(50) NULL,
	VALUE  VARCHAR(100) NULL,
	ATTRIBUTE_ID  INTEGER NULL
)
;



ALTER TABLE PRODUCT_ATTRIBUTE
	ADD  PRIMARY KEY (ATTRIBUTE_ID,PRODUCT_ID)
;



CREATE TABLE PRODUCT_TYPE
(
	TYPE_ID  INTEGER NULL,
	NAME  VARCHAR(50) NULL,
	DESCRIPTION  VARCHAR(100) NULL
)
;



ALTER TABLE PRODUCT_TYPE
	ADD  PRIMARY KEY (TYPE_ID)
;



CREATE TABLE RESOURCE_GROUP
(
	RESOURCE_ID  INTEGER NOT NULL,
	GROUP_ID  INTEGER NOT NULL
)
;



ALTER TABLE RESOURCE_GROUP
	ADD  PRIMARY KEY (RESOURCE_ID,GROUP_ID)
;



CREATE TABLE TYPE_ATTRIBUTE
(
	ATTRIBTE_ID  INTEGER NULL,
	TYPE_ID  INTEGER NOT NULL,
	NAME  VARCHAR(50) NULL,
	DEFAULT_VALUE  VARCHAR(100) NULL
)
;



ALTER TABLE TYPE_ATTRIBUTE
	ADD  PRIMARY KEY (ATTRIBTE_ID,TYPE_ID)
;



CREATE TABLE UORDER
(
	ORDER_ID  INTEGER NULL,
	FIRSTNAME  VARCHAR(32) NULL,
	LASTNAME  VARCHAR(32) NULL,
	EMAIL  VARCHAR(32) NULL,
	TELEPHONE  VARCHAR(20) NULL,
	COMMENT  VARCHAR(64) NULL,
	TOTAL  INTEGER NULL,
	ORDER_STATUS_ID  INTEGER NULL,
	USER_ID  INTEGER NOT NULL,
	CREATED_BY  VARCHAR(32) NULL,
	CREATED_DATE  DATE NULL,
	EDIT_BY  VARCHAR(32) NULL,
	EDIT_DATE  DATE NULL
)
;



ALTER TABLE UORDER
	ADD  PRIMARY KEY (ORDER_ID)
;



CREATE TABLE USER_GROUP
(
	GROUP_ID  INTEGER NULL,
	NAME  VARCHAR(32) NULL,
	DESCRIPTION  VARCHAR(300) NULL,
	CREATED_BY  VARCHAR(32) NULL,
	CREATED_DATE  DATE NULL,
	EDIT_BY  VARCHAR(32) NULL,
	EDIT_DATE  DATE NULL
)
;



ALTER TABLE USER_GROUP
	ADD  PRIMARY KEY (GROUP_ID)
;



CREATE TABLE USER_STATUS
(
	USER_STATUS_ID  INTEGER NULL,
	NAME  VARCHAR(32) NULL
)
;



ALTER TABLE USER_STATUS
	ADD  PRIMARY KEY (USER_STATUS_ID)
;



CREATE TABLE USER_WISH
(
	CUSTOMER_WISH_ID  INTEGER NULL,
	DESCRIPTION  VARCHAR(1024) NULL,
	USER_ID  INTEGER NOT NULL,
	CREATED_BY  VARCHAR(32) NULL,
	CREATED_DATE  DATE NULL,
	EDIT_BY  VARCHAR(32) NULL,
	EDIT_DATE  DATE NULL
)
;



ALTER TABLE USER_WISH
	ADD  PRIMARY KEY (CUSTOMER_WISH_ID)
;



CREATE TABLE USERS
(
	USER_ID  INTEGER NULL,
	USERNAME  VARCHAR(32) NULL,
	PASSWORD  VARCHAR(32) NULL,
	FIRSTNAME  VARCHAR(32) NULL,
	LASTNAME  VARCHAR(32) NULL,
	PATRONYMIC  VARCHAR(32) NULL,
	EMAIL  VARCHAR(32) NULL,
	CODE  VARCHAR(32) NULL,
	CREATED_DATE  DATE NULL,
	EDIT_DATE  DATE NULL,
	USER_STATUS_ID  INTEGER NOT NULL,
	IP  VARCHAR(20) NULL,
	GROUP_ID  INTEGER NOT NULL,
	APPROVED  INTEGER NULL,
	CREATED_BY  VARCHAR(32) NULL,
	EDIT_BY  VARCHAR(32) NULL
)
;



ALTER TABLE USERS
	ADD  PRIMARY KEY (USER_ID)
;



ALTER TABLE ORDER_PRODUCT
	ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
;


ALTER TABLE ORDER_PRODUCT
	ADD FOREIGN KEY (ORDER_ID) REFERENCES UORDER(ORDER_ID)
;



ALTER TABLE PRODUCT
	ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
;


ALTER TABLE PRODUCT
	ADD FOREIGN KEY (TYPE_ID) REFERENCES PRODUCT_TYPE(TYPE_ID)
;



ALTER TABLE PRODUCT_ATTRIBUTE
	ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
;



ALTER TABLE RESOURCE_GROUP
	ADD FOREIGN KEY (RESOURCE_ID) REFERENCES APP_RESOURCE(RESOURCE_ID)
;


ALTER TABLE RESOURCE_GROUP
	ADD FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUP(GROUP_ID)
;



ALTER TABLE TYPE_ATTRIBUTE
	ADD FOREIGN KEY (TYPE_ID) REFERENCES PRODUCT_TYPE(TYPE_ID)
;



ALTER TABLE UORDER
	ADD FOREIGN KEY (ORDER_STATUS_ID) REFERENCES ORDER_STATUS(ORDER_STATUS_ID)
;


ALTER TABLE UORDER
	ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
;



ALTER TABLE USER_WISH
	ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
;



ALTER TABLE USERS
	ADD FOREIGN KEY (USER_STATUS_ID) REFERENCES USER_STATUS(USER_STATUS_ID)
;


ALTER TABLE USERS
	ADD FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUP(GROUP_ID)
;


